name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona tu repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instala dependencias (en la raíz)
      - name: Install dependencies
        run: npm install

      # Ejecuta pruebas
      - name: Run tests
        run: npm test
